### ISSUE TITLE
BluetoothManager/BluetoothManager.h not found.

### ISSUE THREAD

**Issue by jagdish24** [michaeldorner/BeeTee#1]
Hey 

I have followed steps of your Github tutorial, But still i have errors. Lexical or Preprocessor issue, BluetoothManager/BluetoothManager.h not found.

Please help me on my query.

Thanks.

**Comment by pallzoltan** [comment]
Digging up an old body, but perhaps you were compiling against the simulator? I think the simulator doesn't have a BluetoothManager lib because BT is not supported in the simulator.
