### ISSUE TITLE
how to make it run on ios9

### ISSUE THREAD

**Issue by lonewolfaka9** [michaeldorner/BeeTee#10]
i'm trying to implment this code using xcode7> and ios9>

any suggestion or tip will be helpfull

**Comment by michaeldorner** [comment]
Just follow exactly the steps mentioned in the readme file.

**Comment by ChrisMash** [comment]
The same file path for the headers doesn't seem to exist...?

**Comment by michaeldorner** [comment]
We have a problem starting with Xcode 7.3: https://github.com/michaeldorner/BeeTee/issues/11
