### ISSUE TITLE
Not working on iOS 10.1.1

### ISSUE THREAD

**Issue by alleview** [michaeldorner/BeeTee#12]
It is not working on iOS 10.1.1

I tried all the suggestions i found around on the web, but didnt work.
It shows first error with 2 functions, which i excluded them and then i am always getting Error: Framework not found BluetoothManager.

I used the bash script to check, and it shows the files are in the correct place and everything. 

Any suggestions anyone?

**Comment by michaeldorner** [comment]
As far as I know Apple removed the options we had already with iOS 9.3 (see issue #11 ). 
But we all are very curious if there is another option. Feel free to investigate! :-)
