### ISSUE TITLE
iOS 11 beta 9 : cannot power on/off Bluetooth

### ISSUE THREAD

**Issue by jbarmanet** [michaeldorner/BeeTee#15]
Did anyone get this issue ? The call to setPowered:YES / NO seems to have no effect, without throwing any kind of error nor warning...

**Comment by michaeldorner** [comment]
Thanks for pointing this out. Unfortunately I haven't install the beta of iOS 11 yet. But I hope I have moment to see the problem as soon as the release candidate is out. 
Anyone else?

**Comment by jbarmanet** [comment]
Weird finding: 
If Bluetooth was powered off from the Control Center, then it is impossible to turn it back on.
However, if you turn Bluetooth off from the Bluetooth Settings, then we can turn Bluetooth back on programmatically! 

This is maybe not a real hope as some other private Bluetooth calls are still blocked, like for example retrieving the list of paired peripherals.

Note: seen after installing iOS 11 beta 10

**Comment by jbarmanet** [comment]
Found the trick... Trying to make a pull request but it fails, faulty rights... Is the repository restricted or should I ask for an authorization?

**Comment by michaeldorner** [comment]
I would love to get a pull request from you. Actually there shouldn't be any problems, there are several pull requests out there. 
What is the error message?

**Comment by jbarmanet** [comment]
GitHub App leaves me with a **Authentication Failed** popup saying: _You may not have permission to access BeeTee. Check Preferences to make sure you’re still logged in._

**Comment by michaeldorner** [comment]
Sounds like [this issue](https://stackoverflow.com/questions/25047468/github-mac-permission-issue).

**Comment by jbarmanet** [comment]
Okay, this whole issue is now useless I was wrong about the issue and will close it, but I will give also some clarifications that might be useful for later issues:

I was using only the `setPowered:` call to reenable Bluetooth, although you use now the `setEnabled:` one. 
And indeed, with `setEnabled:` you have no issue with iOS11. That is why the original issue posted can be forgotten. 

**Now, to whom wants to go further about iOS11 changes:**

Notice this subtle change when you use the `setPowered:` call with iOS11:

If it was previously disabled from Settings > Bluetooth, then `setPowered:YES` works as expected. Nothing to add. 

If you previously disabled Bluetooth from Control Center, then you will see the Bluetooth back on in Settings > Bluetooth but you won't see the Bluetooth status bar icon appear, and you won't be able to scan for devices... all will look like if Bluetooth was remaining disabled. 
Moreover, in this case you can see a new line appearing in Settings > Bluetooth saying something like: _Authorize new connections, The new Bluetooth connexions have been deactivated from the control center._  

I found that it had something to do with a new property added into BluetoothManager.h, called blacklist, and that can have 2 states, enabled or disabled. With iOS11 you will find those 2 new things among others:
```
- (bool)blacklistEnabled;
- (void)setBlacklistEnabled:(bool)arg1;
```

And there you go: you can know if blacklist is enabled, and you can also disable it when trying to power bluetooth on… and it works!

**Comment by michaeldorner** [comment]
Please correct me if I am wrong: You need to disable the blacklist to turn Bluetooth on and off?

**Comment by jbarmanet** [comment]
Sorry if I was confusing.

When using `setEnabled:` you never need to `setBlacklistEnabled:`
But if you want to use `setPowered:Yes` you might need to `setBlacklistEnabled:No` if `blacklistEnabled` was Yes, because otherwise you won't be able to get Bluetooth only with `setPowered:Yes`.  

It looks like iOS11 introduces some granularity in Bluetooth management depending from where the user set it on or off. Bluetooth can be powered on but look like it's not when blacklist is enabled. 

Don't hesitate to ask again if I'm not clear.

**Comment by michaeldorner** [comment]
Thanks for the explanation:

So the steps should be:

1. `setBlacklistEnabled:NO`
2. `setPowered:NO`

Now Blueooth is off.

3. `setPowered:YES`
4. `setBlacklistEnabled:YES ` (make sure that everything works fine again)

Now Bluetooth is on. 

Am I right?

**Comment by jbarmanet** [comment]
You were not far, but blacklist needs to be _disabled_ in order for Bluetooth to work. 
It gives:

1. `setBlacklistEnabled:YES` >> **this is optional** unless we know if blacklist was enabled or not before powering BT on, then yes, we might want to put things back to what they were. 
2. `setPowered:NO`

Then 

3. `setPowered:YES`
4. `setBlacklistEnabled:NO` **>> this is mandatory** to ensure Bluetooth works. Optionnally before doing this, we could store somewhere the initial state of blacklist, in order to know what is was, and setup its initial value when we will later set bluetooth back to off (see point 1.) 

All of this is a matter of granularity: Bluetooth and blacklist seem to be 2 independant settings.
The Bluetooth could be enabled although blacklist is also enabled. 
The key-thing here, is to know that when blacklist is enabled, then bluetooth cannot be really turned on and used with setPowered:Yes. The inverse is not true.

**Comment by michaeldorner** [comment]
Perfect, thanks!

**Comment by michaeldorner** [comment]
I think [this Apple support document ](https://support.apple.com/en-us/HT208086)is related to this new way of trigger.

**Comment by jbarmanet** [comment]
Good catch, that's it!
