### ISSUE TITLE
Change Bluetooth name of iOS device?

### ISSUE THREAD

**Issue by NgNivida** [michaeldorner/BeeTee#18]
Hi 

This is one of the best repository that we are using in our code for bluetooth connection related functionality. Do you have any idea that can we change Bluetooth name of the device?

**Comment by michaeldorner** [comment]
Do you mean the name of the connecting or the name of the connected device?

**Comment by NgNivida** [comment]
The device which is trying to connect to other devices.
My app is installed on this device  and I want to update its Bluetooth name programmatically.

**Comment by michaeldorner** [comment]
The Bluetooth name of the iPhone which runs BeeTee? I believe there is no way to do so. But who knows - it is all undocumented. I would be happy to get a PR, if you find a way! It
