### ISSUE TITLE
 Cannot connect to other hardware.

### ISSUE THREAD

**Issue by DoHienHDT** [michaeldorner/BeeTee#24]
Thank you for a great idea, I used your beetee application and if you don't mind I can ask you a question: The application only scans devices and I want to connect to one device. I have a sensor, I can't connect to my sensor. Do you have any solution?
Thank you very much

**Comment by michaeldorner** [comment]
Unfortunately, I have no experiences with doing so. [There was an attempt](https://github.com/michaeldorner/BeeTee/issues/2), but I am not aware that it worked. If your sensor supports [BLE](https://en.wikipedia.org/wiki/Bluetooth_Low_Energy), the Apple's framework [Core Bluetooth](https://developer.apple.com/documentation/corebluetooth) is the right framework to use.

**Comment by DoHienHDT** [comment]
Thanks for your answer, I tried Core Bluetooth but I can't get localAddress
but only get the uuid of the sensor or another device, do you have any
solution for this case?


Vào Th 6, 9 thg 8, 2019 vào lúc 08:53 Michael Dorner <
notifications@github.com> đã viết:

**Comment by dohien1109** [comment]
Thanks for your answer, I tried Core Bluetooth but I can't get localAddress but only get the uuid of the sensor or another device, do you have any solution for this case?
