### ISSUE TITLE
Not Scanning BLE devices

### ISSUE THREAD

**Issue by nitinAgnihotriCHM** [michaeldorner/BeeTee#25]
In there any way to scan BLE devices, because it is scanning only the Bluetooth classic devices.
I have requirements where I want to scan bluetooth classics as well as BLE devices using bluetooth 4.0 or 5.0 versions.
Please let me know if there's a way to do the same.

**Comment by michaeldorner** [comment]
No, BeeTee just scans for non-BLE devices. For BLE devices you should use the framework [Core Bluetooth](https://developer.apple.com/documentation/corebluetooth).
