### ISSUE TITLE
armv7 architecture and iPhone 5s does not work

### ISSUE THREAD

**Issue by xurayg** [michaeldorner/BeeTee#4]
If architectures are set to be "armv7" and the device is iphone5s, then it will not work ,is there any solution for that? like this: http://stackoverflow.com/questions/19858710/bluetoothmanager-not-working-on-ios-7   @a2hill mentioned .

**Comment by michaeldorner** [comment]
This is not true. The demo application was made on an iPhone 5S with the set architecture of armv7.

**Comment by xurayg** [comment]
Thank you for your answer , but I tried it with this . It is really not work.. Please give me  some tips~
![image](https://cloud.githubusercontent.com/assets/7018319/7645675/2e600018-faeb-11e4-8611-c77f471e1de9.png)
and then : 
![image](https://cloud.githubusercontent.com/assets/7018319/7645693/55b1dc5e-faeb-11e4-8b1d-b3ddc8e5df6f.png)

**Comment by xurayg** [comment]
@michaeldorner I also check it on iPhone5C with iOS8.1.1 and  the set architecture of armv7, it is the same issue.   I'd be very grateful  If you could help me to check it !

**Comment by michaeldorner** [comment]
Please check out the new version 3.0.

**Comment by xurayg** [comment]
It works !!!
