### ISSUE TITLE
Swift Compatibility

### ISSUE THREAD

**Issue by akatzbreaker** [michaeldorner/BeeTee#5]
Hi,

I know it might be a little bit out of topic. But I would really appreciate some help here...

So, I am working on a Swift project on iOS 8.4. I have the private framework imported and these Files of your Project:
- MDBluetoothDevice.h
- MDBluetoothDevice.m
- MDBluetoothManager.h
- MDBluetoothManager.m
- MDBluetoothObserver.h

I created the bridging header and is set up to include these files (and the private framework)
Then, I create an object like this:
`var BluetoothMng: MDBluetoothManager = MDBluetoothManager()`
       
Even though the BluetoothMng is initialised, when I run these the value is always false:
`BluetoothMng.bluetoothIsAvailable()
BluetoothMng.bluetoothIsPowered()`

even if the Bluetooth is Enabled.
Also, when I use this, nothing happens:
`BluetoothMng.turnBluetoothOn()`

Any Ideas how to fix the issue?
Thanks!

**Comment by michaeldorner** [comment]
I haven't tried to use BeeTee in Swift. But I would appreciate if you could share your experiences with me.

**Comment by akatzbreaker** [comment]
I also tried with this:
`var BluetoothMng: MDBluetoothManager = MDBluetoothManager.sharedInstance()`

Still doesn't work.... Trying to figure out what is going on...

**Comment by akatzbreaker** [comment]
I got it working for my Application! It works actually pretty well. This is how to get it working for anyone interested:

1) Setup the Private framework headers as explained in the repository's README

2) Import these Files to your Project:
>MDBluetoothDevice.h
>MDBluetoothDevice.m
>MDBluetoothManager.h
>MDBluetoothManager.m
>MDBluetoothObserver.h


3) Add the Bridging Header (*as Xcode will prompt*)

4) In the Bridging Header file add these:
```#import "MDBluetoothDevice.h"```
```#import "MDBluetoothManager.h"```
```#import "MDBluetoothObserver.h"```
```#import <BluetoothManager/BluetoothManager.h>```
```#import "BTHandler.h"```

5) Create a Bluetooth Manager shared instance as below:

`var BluetoothManager: MDBluetoothManager = MDBluetoothManager.sharedInstance()`
        
6) Use the methods as usual:
`BluetoothManager.turnBluetoothOn()`


I didn't use any Notifications actually so I guess if someone wants to, he should create a Notification observer and register it through:
`BluetoothManager.registerObserver(<#observer: MDBluetoothObserverProtocol!#>)`


I hope this helps!

**Comment by michaeldorner** [comment]
Thanks alot!

**Comment by jbarmanet** [comment]
For who this might help, a better explanation to register the notification / observer in swift, thanks to [this answer on stackoverflow](http://stackoverflow.com/a/31002924/1720332)...
