### ISSUE TITLE
version of Xcode ?

### ISSUE THREAD

**Issue by imanupgupta** [michaeldorner/BeeTee#8]
what version of Xcode in which you develop this code because this is show error in Xcode 7. there are no framework  ** ##import < BluetoothManager/BluetoothDevice.h > **rather then is framework there are have another framework which is **# #import < CoreBluetooth/CoreBluetooth.h > **so that its not work in my code now what should i @michaeldorner

**Comment by michaeldorner** [comment]
This is not related to a Xcode version. Please read the introduction carefully. If you follow this steps exactly, it works fine.

**Comment by imanupgupta** [comment]
in my Xcode 7 no **# import < BluetoothManager/BluetoothDevice.h >** package is not present.
there are have ****# import < CoreBluetooth/CoreBluetooth.h >***

**Comment by imanupgupta** [comment]
http://stackoverflow.com/questions/25394040/cannot-compile-beetee-framework-because-of-missing-bluetoothdevice-h-file

**Comment by imanupgupta** [comment]
thank you sir yesterday i was open your code again and under stand everything very easily and configure the code. this is not a version problem of Xcode I am new in Xcode thats why i was getting problem but right now i got understand. thank you so much.. :)
